# Generated by Django 5.0.6 on 2024-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField(default="")),
                ("emergency_contact_name", models.CharField(max_length=255)),
                ("emergency_contact_relationship", models.CharField(max_length=255)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("emergency_contact_email", models.EmailField(max_length=254)),
                ("medical_qualifications", models.TextField()),
                ("years_of_experience", models.IntegerField()),
                ("current_practice_location", models.CharField(max_length=255)),
                ("professional_associations", models.TextField()),
                ("research_interests", models.TextField()),
                ("insurance_provider", models.CharField(max_length=255)),
                ("policy_number", models.CharField(max_length=255)),
                ("group_number", models.CharField(max_length=255)),
                ("coverage_details", models.TextField()),
                ("hospital_affiliation", models.CharField(max_length=255)),
                ("languages_spoken", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("confirm_password", models.CharField(max_length=255)),
                ("enable_2fa", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
